[package]
name = "vettore"
version = "0.3.5"
authors = []
edition = "2021"
rust-version = "1.91"

[lib]
name = "vettore"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
bytemuck = "1.25.0"
pollster = "1.0.0"
rustler = { version = "0.38.0", default-features = false }
wide = "1.5.0"
wgpu = { version = "30.0.1", default-features = false, features = ["std", "parking_lot", "dx12", "metal", "gles", "vulkan", "wgsl"] }

[dev-dependencies]
naga = { version = "30.0.1", features = ["wgsl-in"] }

[features]
default = ["nif_version_2_15"]
nif_version_2_15 = ["rustler/nif_version_2_15"]
nif_version_2_16 = ["rustler/nif_version_2_16"]

[profile.release]
codegen-units = 1
lto = true
panic = "unwind"
strip = "debuginfo"
