[package]
name = "vettore"
version = "0.1.6"
authors = []
edition = "2021"

[lib]
name = "vettore"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rand = "0.9.0"
rustler = "0.36.1"
wide = "0.7.32"

[profile.release]
codegen-units = 1
lto = true
panic = 'abort'
strip = "debuginfo"